# Generated by Django 3.1.7 on 2021-11-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unitss', to='users.landlord'),
        ),
    ]
