# Generated by Django 3.2.9 on 2021-11-22 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, choices=[('ACH', 'ACH'), ('DEBIT CARD', 'DEBIT CARD'), ('CREDIT CARD', 'CREDIT CARD')], max_length=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('PAUSED', 'PAUSED')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('ACH', 'ACH'), ('DEBIT', 'DEBIT'), ('CREDIT', 'CREDIT')], max_length=6, null=True)),
                ('amount_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_paid', models.FloatField(blank=True, default=0.0, null=True)),
                ('due_date', models.DateTimeField()),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=9, null=True)),
                ('scheduled_pay_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('ACH', 'ACH'), ('DEBIT CARD', 'DEBIT CARD'), ('CREDIT CARD', 'CREDIT CARD')], max_length=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_to_pay', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_scheduled', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('PLUMBING', 'PLUMBING'), ('KITCHEN', 'KITCHEN'), ('ELECTRICITY', 'ELECTRICITY'), ('YARD', 'YARD'), ('GARAGE', 'GARAGE'), ('AIR CONDITIONING', 'AIR CONDITIONING'), ('OTHER', 'OTHER')], max_length=16, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')], default='PENDING', max_length=11, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('URGENT', 'URGENT')], default='low', max_length=11, null=True)),
            ],
        ),
    ]
