# Generated by Django 3.2.9 on 2021-11-22 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequests',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicerequests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequests',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicerequests', to='users.unit'),
        ),
        migrations.AddField(
            model_name='scheduledpayments',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='tenant.invoice'),
        ),
        migrations.AddField(
            model_name='scheduledpayments',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant.invoice'),
        ),
        migrations.AddField(
            model_name='payments',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
